name: bubble
description: A Flutter widget for chat like a speech bubble in Whatsapp and others.
version: 1.2.1
homepage: https://github.com/vi-k/bubble

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
